version: '3'
services:
  db:
    container_name: postgres
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - postgre.env

    volumes:
      - ./db-data/:/var/lib/postgresql/data/