spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/crypto
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false

  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yml

input:
  files:
    location: C:\\Users\\Grigor_Tumanyan\\Desktop\\java_mid_level_backend_exercise\\prices\\

